import Head from 'next/head'
import Post from 'components/Post'

export default function post() {
    return (
      <>
        <Head>
          <title>Post</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="">
          <div className="flex">
            <img className="max-w-sm border" src="wojak.jpg"></img>
            <div className="flex flex-col justify-center gap-4">
              <p>Education: </p>
              <p>Interests: </p>
              <p>About me: </p>
            </div>
          </div>
          {/* Show posts that belong to this user here */}
          <div className='flex flex-row gap-12 justify-center mt-6'>
            <Post />
            <Post />
            <Post />
          </div>
        </main>
      </>
    );
  }