import Head from 'next/head'

export default function post() {
    return (
      <>
        <Head>
          <title>Post</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="">
            <h1 className="flex min-h-screen items-center justify-center">Account creation coming soon!</h1>
        </main>
      </>
    );
  }