import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import NavBar from 'components/NavigationBar'
import SideBar from 'components/SideBar'
import Post from 'components/Post'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Feed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {/* Navbar and sidebar (and footer when we have one) could be put in 
        something actually called a 'hero' component */}
        <NavBar />
        <SideBar/>
        <Post />
        <Post />
        <Post />
      </main>
    </>
  )
}
