import Head from 'next/head'
import Image from 'next/image'
import SideBar from 'components/SideBar'
import Post from 'components/Post'

export default function Home() {
  return (
    <>
      <Head>
        <title>Feed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <SideBar/>
        <div className="bg-gray-100 p-4 flex flex-wrap">
          <Post />
          <Post />
          <Post />
          <Post />
          <Post />
          <Post />
          <Post />
          <Post />
          <Post />
          <Post />
          <Post />
          <Post />
        </div>
      </main>
    </>
  )
}
