import Head from 'next/head'
import NavBar from 'components/NavigationBar'
import SideBar from 'components/SideBar'
export default function post() {
    return (
      <>
        <Head>
          <title>Post</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex">
          <div>
            <SideBar />
          </div>
          <div>
            {/* This image will later be the actual graph of data */}
            <img className="w-2/4" src="test_img.png" />
            <p>
              Here is more detailed information about this data such as:{" "}
              <br></br>* Our findings <br></br>* where the data came from{" "}
              <br></br>* transformations on the data <br></br>
            </p>
          </div>
        </main>
      </>
    );
  }
